name: recipely
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  bloc_test: ^9.1.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  firebase_crashlytics: ^3.3.0
  flutter: 
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.8.1
  fpdart: ^0.6.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  go_router: ^7.0.1
  google_fonts: ^4.0.4
  injectable: ^2.1.1
  json_annotation: ^4.8.1
  mockito: ^5.4.0
  pubspec_dependency_sorter: ^1.0.3
  very_good_analysis: ^4.0.0+1

dev_dependencies: 
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.6.2
flutter: 
  uses-material-design: true
